"""add_risk_definition_column

Revision ID: 1543f8b62089
Revises: 001_multi_framework
Create Date: 2026-01-22 21:58:20.375565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1543f8b62089'
down_revision = '001_multi_framework'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('risk_definition', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'risk_definition')
    # ### end Alembic commands ###