#!/bin/bash
# MetricFrame — Enable HTTPS
# Run this to add TLS encryption to an existing MetricFrame installation.
#
# Usage:
#   cd ~/metricframe && curl -fsSL https://get.metricframe.ai/enable-tls.sh | bash
#   OR
#   ./enable-tls.sh [install_directory]

set -euo pipefail

INSTALL_DIR="${1:-${METRICFRAME_HOME:-$HOME/metricframe}}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo "============================================"
echo "  MetricFrame — Enable HTTPS"
echo "============================================"
echo ""

# Verify install directory
if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
    error "MetricFrame installation not found at $INSTALL_DIR. Pass the install directory as an argument."
fi

info "Install directory: $INSTALL_DIR"
cd "$INSTALL_DIR"

# Check if already enabled
if [ -f "docker-compose.override.yml" ] && [ -f "nginx-tls.conf" ] && [ -d "certs" ]; then
    warn "HTTPS appears to already be configured."
    echo "  To regenerate the certificate, delete the certs/ directory and run this script again."
    exit 0
fi

# Generate certificate
info "Generating TLS certificate..."
mkdir -p certs

if docker run --rm \
    -v "$PWD/certs:/certs" \
    ghcr.io/automationacct01/metric_frame-backend:latest \
    python3 -m src.services.tls_cert /certs metricframe 2>/dev/null; then
    success "TLS certificate generated"
else
    error "Failed to generate TLS certificate. Make sure the MetricFrame backend image is available."
fi

# Create docker-compose override
info "Creating docker-compose.override.yml..."
cat > docker-compose.override.yml << 'OVERRIDE_EOF'
# MetricFrame TLS Override (generated by enable-tls.sh)
services:
  frontend:
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-tls.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    environment:
      CORS_ORIGINS: http://localhost,http://localhost:3000,https://localhost,https://localhost:3000
OVERRIDE_EOF
success "Created docker-compose.override.yml"

# Create TLS nginx config
info "Creating nginx-tls.conf..."
cat > nginx-tls.conf << 'NGINX_EOF'
# MetricFrame HTTPS server on port 3000
server {
    listen 3000 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/metricframe.crt;
    ssl_certificate_key /etc/nginx/certs/metricframe.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript application/json;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }

    location /health {
        proxy_pass http://backend:8000/health;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://localhost:* http://localhost:* https://api.anthropic.com https://api.openai.com https://api.together.xyz;" always;
}
NGINX_EOF
success "Created nginx-tls.conf"

# Restart containers
info "Restarting MetricFrame with HTTPS..."
docker compose down 2>/dev/null &
STOP_PID=$!
ELAPSED=0
while kill -0 $STOP_PID 2>/dev/null; do
    if [ $ELAPSED -ge 60 ]; then
        kill $STOP_PID 2>/dev/null; wait $STOP_PID 2>/dev/null
        warn "Timed out stopping containers. Trying force..."
        docker compose kill 2>/dev/null
        break
    fi
    sleep 2; ELAPSED=$((ELAPSED + 2))
done
wait $STOP_PID 2>/dev/null

docker compose up -d 2>&1 &
START_PID=$!
ELAPSED=0
while kill -0 $START_PID 2>/dev/null; do
    if [ $ELAPSED -ge 120 ]; then
        kill $START_PID 2>/dev/null; wait $START_PID 2>/dev/null
        error "Failed to start containers. Run 'docker compose logs' for details."
    fi
    sleep 2; ELAPSED=$((ELAPSED + 2))
done
wait $START_PID || error "Failed to start containers. Run 'docker compose logs' for details."

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  HTTPS is now enabled!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "  Open your browser to: https://localhost:3000"
echo ""
echo -e "  ${YELLOW}Browser Certificate Warning (one-time):${NC}"
echo "  Your browser will show 'Your connection is not private'."
echo "  This is expected — MetricFrame uses a self-signed certificate."
echo "  Click 'Advanced' → 'Proceed to localhost' to continue."
echo "  You only need to do this once."
echo ""
echo "  To disable HTTPS later:"
echo "    curl -fsSL https://get.metricframe.ai/disable-tls.sh | bash"
echo ""
